#!/usr/bin/env python3
"""
Patch: agent/prompt_builder.py

Adds:
  1. GENUI_GUIDANCE constant — full static block reference (prefix-cacheable)
  2. "desktop" entry in PLATFORM_HINTS dict

The guidance is intentionally a single static string with no dynamic content.
This ensures the KV cache prefix hash stays stable across requests, making
the ~1,500 tokens effectively free after the first cache fill.

Anchors:
  - DEVELOPER_ROLE_MODELS constant (stable insertion point)
  - PLATFORM_HINTS dict literal (stable — used by all platforms)
"""

import sys
from pathlib import Path

# Add overlay root to path for patch_utils
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
from patch_utils import FilePatcher, PatchError

OVERLAY_ROOT = Path(__file__).resolve().parent.parent.parent
AGENT_DIR = OVERLAY_ROOT / "hermes-agent"
TARGET = AGENT_DIR / "agent" / "prompt_builder.py"

# Full static block reference — designed to be prefix-cached.
# No dynamic content (no timestamps, no template lists, no per-user data).
GENUI_GUIDANCE_BLOCK = r'''
# ---------------------------------------------------------------------------
# GenUI (Generative UI) guidance — full composable block reference.
# Static content optimized for LLM prefix caching (KV cache reuse).
# [GENUI-OVERLAY] Auto-generated by hermes-genui-overlay
# ---------------------------------------------------------------------------

GENUI_GUIDANCE = (
    "# Generative UI (GenUI) — Composable Interactive Widgets\n"
    "You can render interactive UI widgets in the chat by emitting a fenced "
    "`genui` code block. Widgets compose from a library of blocks — you build "
    "nested component trees in JSON.\n\n"

    "## When to Use\n"
    "Use widgets when interactive UI serves the user better than plain text: "
    "forms, confirmations, wizards, dashboards, actionable cards. "
    "Do NOT use widgets for simple yes/no or when plain text suffices.\n\n"

    "## Payload Structure\n"
    "Emit exactly ONE ```genui block per response. Required top-level fields:\n"
    "- **widgetId** (string): Unique ID, e.g. 'order-form-42'.\n"
    "- **widgetType** (string): Always `\"composition\"` for composable widgets.\n"
    "- **initialState** (object): Default values for ALL bound fields.\n"
    "- **trackedFields** (array): `[{key, tracking}]` — declares observed fields.\n"
    "- **actions** (array): `[{id, label, style, tracking}]` — button actions.\n"
    "- **children** (array): The block tree.\n"
    "- **initialPage** (string, optional): Starting page ID for multi-page.\n\n"

    "## CRITICAL RULES\n"
    "1. Every `bind` field MUST be in BOTH `initialState` AND `trackedFields`.\n"
    "2. Every `actionId` on a Button MUST match an entry in `actions`.\n"
    "3. Use `\"reply\"` tracking on 1-2 submit buttons ONLY.\n"
    "4. Use `\"context\"` tracking on most form fields.\n"
    "5. Forgetting tracking = field defaults to `\"ignored\"` = you NEVER see input.\n\n"

    "## Block Node Shape\n"
    "`{type, props, children, bind, navigate, style, key}`\n\n"

    "## Block Reference\n\n"

    "### Layout Blocks\n"
    "- **Stack**: `{direction: vertical|horizontal, gap: none|xs|sm|md|lg|xl, "
    "align: start|center|end|stretch, justify: start|center|end|between|around, "
    "wrap: bool, padding: none|sm|md|lg}`\n"
    "- **Grid**: `{columns: number(2), gap, minChildWidth: string}`\n"
    "- **Card**: `{title, subtitle, variant: default|outlined|elevated|ghost, "
    "collapsible: bool, defaultCollapsed: bool}`\n"
    "- **PageView**: Multi-page container. Children MUST be Page blocks. "
    "Set `initialPage` at payload root.\n"
    "- **Page**: `{pageId: string(REQUIRED), title: string}` — inside PageView.\n"
    "- **Tabs**: `{defaultTab: number(0)}` — each child's `props.label` = tab title.\n"
    "- **Accordion**: `{allowMultiple: bool(false)}` — each child's `props.label` = section header.\n"
    "- **Divider**: `{label: string}` — horizontal rule.\n"
    "- **Spacer**: `{size: sm|md|lg|xl}` — fixed spacing.\n\n"

    "### Content Blocks\n"
    "- **Text**: `{content(REQUIRED), variant: h1|h2|h3|body|caption|code|label, "
    "color, weight: normal|medium|semibold|bold, align: left|center|right}`\n"
    "- **Badge**: `{label(REQUIRED), color: green|red|yellow|blue|purple|gray, "
    "variant: solid|outline|subtle}`\n"
    "- **Stat**: `{label(REQUIRED), value(REQUIRED), change, "
    "trend: up|down|neutral, prefix, suffix}`\n"
    "- **ProgressBar**: `{value(REQUIRED), max: 100, label, color, showValue: bool}`\n"
    "- **Alert**: `{message(REQUIRED), variant: info|success|warning|error, "
    "dismissible: bool}`\n"
    "- **Image**: `{src(REQUIRED), alt, width, height, fit, rounded: bool}`\n"
    "- **KeyValue**: `{entries: [{key, value}]}`\n"
    "- **List**: `{items: [string], ordered: bool, variant: bullet|numbered|none}`\n\n"

    "### Interactive Blocks (ALL use `bind`)\n"
    "- **Input**: `{label, placeholder, type: text|number|email|password}` — bind: string|number\n"
    "- **TextArea**: `{label, placeholder, rows: 3}` — bind: string\n"
    "- **Select**: `{label, options: [{label,value}](REQUIRED), placeholder}` — bind: string\n"
    "- **Checkbox**: `{label(REQUIRED)}` — bind: boolean\n"
    "- **RadioGroup**: `{label, options: [{label,value}](REQUIRED)}` — bind: string\n"
    "- **Slider**: `{label, min: 0, max: 100, step: 1, showValue: bool}` — bind: number\n"
    "- **Button**: `{label(REQUIRED), style: primary|secondary|danger|ghost, "
    "actionId, disabled, loading}`. Use `navigate` for page nav. NO bind.\n\n"

    "### Data Blocks\n"
    "- **DataTable**: `{columns: [{key,label,format?}](REQUIRED), rows: [{...}], "
    "striped: bool, compact: bool}`. format: currency|number|date. Can bind for dynamic rows.\n\n"

    "## 4-Tier Tracking\n"
    "- **ignored**: Never sent. For UI-only state.\n"
    "- **context**: Silently merged into background. Use for most form fields.\n"
    "- **explicit**: Attached as structured data to next message.\n"
    "- **reply**: Triggers immediate agent reply. Use for submit buttons only (1-2 max).\n\n"

    "## Multi-Page Pattern\n"
    "Use PageView + Page + Button with `navigate`:\n"
    "1. Set `initialPage` at payload root (not inside PageView)\n"
    "2. Each Page needs unique `pageId`\n"
    "3. Navigate via `{\"type\": \"Button\", \"navigate\": \"step2\"}`\n"
    "4. Submit button on last page uses `actionId` + `reply` tracking\n"
    "5. ALL bound fields across ALL pages go in ONE `initialState` and ONE `trackedFields`\n\n"

    "## Example: Multi-Page Wizard\n"
    "```genui\n"
    "{\n"
    "  \"widgetId\": \"signup\",\n"
    "  \"widgetType\": \"composition\",\n"
    "  \"initialState\": {\"name\": \"\", \"plan\": \"\"},\n"
    "  \"initialPage\": \"info\",\n"
    "  \"trackedFields\": [\n"
    "    {\"key\": \"name\", \"tracking\": \"context\"},\n"
    "    {\"key\": \"plan\", \"tracking\": \"context\"}\n"
    "  ],\n"
    "  \"actions\": [{\"id\": \"done\", \"label\": \"Done\", \"style\": \"primary\", \"tracking\": \"reply\"}],\n"
    "  \"children\": [{\"type\": \"PageView\", \"children\": [\n"
    "    {\"type\": \"Page\", \"props\": {\"pageId\": \"info\", \"title\": \"Info\"}, \"children\": [\n"
    "      {\"type\": \"Stack\", \"props\": {\"gap\": \"md\"}, \"children\": [\n"
    "        {\"type\": \"Input\", \"props\": {\"label\": \"Name\"}, \"bind\": \"name\"},\n"
    "        {\"type\": \"Button\", \"props\": {\"label\": \"Next\"}, \"navigate\": \"plan\"}\n"
    "      ]}\n"
    "    ]},\n"
    "    {\"type\": \"Page\", \"props\": {\"pageId\": \"plan\", \"title\": \"Plan\"}, \"children\": [\n"
    "      {\"type\": \"Stack\", \"props\": {\"gap\": \"md\"}, \"children\": [\n"
    "        {\"type\": \"RadioGroup\", \"props\": {\"options\": [{\"label\": \"Free\", \"value\": \"free\"}, {\"label\": \"Pro\", \"value\": \"pro\"}]}, \"bind\": \"plan\"},\n"
    "        {\"type\": \"Stack\", \"props\": {\"direction\": \"horizontal\", \"justify\": \"between\"}, \"children\": [\n"
    "          {\"type\": \"Button\", \"props\": {\"label\": \"Back\", \"style\": \"ghost\"}, \"navigate\": \"info\"},\n"
    "          {\"type\": \"Button\", \"props\": {\"label\": \"Complete\", \"style\": \"primary\", \"actionId\": \"done\"}}\n"
    "        ]}\n"
    "      ]}\n"
    "    ]}\n"
    "  ]}]\n"
    "}\n"
    "```\n"
)
'''


def apply():
    try:
        patcher = FilePatcher(TARGET)

        # 1. Insert GENUI_GUIDANCE constant after DEVELOPER_ROLE_MODELS
        patcher.insert_after(
            anchor='DEVELOPER_ROLE_MODELS = ("gpt-5", "codex")',
            insertion=GENUI_GUIDANCE_BLOCK,
            name="Add GENUI_GUIDANCE constant",
            marker="[GENUI-OVERLAY]",
        )

        # 2. Add "desktop" to PLATFORM_HINTS dict
        patcher.append_to_dict(
            dict_anchor="PLATFORM_HINTS = {",
            key='"desktop"',
            value='(\n'
                  '        "You are in the Hermes Desktop application, a native Electron-based "\n'
                  '        "chat interface with full Markdown rendering support — headings, bold, "\n'
                  '        "italic, code blocks, tables, and syntax highlighting all render natively. "\n'
                  '        "This platform supports Generative UI (GenUI): you can render interactive "\n'
                  '        "React widgets directly in the chat thread by emitting ```genui code "\n'
                  '        "blocks. You have a full library of composable UI blocks — see the GenUI "\n'
                  '        "guidance in your system prompt for the complete block reference. Prefer "\n'
                  '        "widgets over plain text when interactive controls would meaningfully "\n'
                  '        "improve the user experience."\n'
                  '    )',
            name='Add "desktop" platform hint',
            marker='"desktop":',
        )

        changed = patcher.write()
        print(patcher.report())
        return changed

    except PatchError as e:
        print(f"  ✗ FAILED: {e}", file=sys.stderr)
        return False


if __name__ == "__main__":
    success = apply()
    sys.exit(0)
